### ISSUE TITLE
Run actions with socket.io

### ISSUE THREAD

**Issue by vkresch** [Alexmhack/Django-Rasa-Sockets#1]
I successfully run your instructions on setting up the chat. However I am not sure how I can run my custom actions and where to put the action folder in the directory. Right now my bot can respond only to simple text message but not to action message (see image below). I put the action folder in rasachat like this: `rasachat/actions/tell_time.py` with tell_time.py:

```
from rasa_core_sdk import Action
from rasa_core_sdk.events import SlotSet
from datetime import datetime
import time


class Inform(Action):

    def name(self):
        return "tell_time"

    def run(self, dispatcher, tracker, domain):
        infoname = tracker.get_slot('info_name')
        response = "The time is " + str(datetime.strftime(datetime.now(), '%H:%M:%S'))

        dispatcher.utter_message(response)
        return [SlotSet("tell_time", tell_time)]

```

I trained the bot intent and story to respond to the time question with calling tell_time.py. Not sure what I am missing right now. I tried adding an action endpoint to my bot.py but it did't work either:
```

from rasa_core.agent import Agent
from rasa_core.channels.socketio import SocketIOInput
from rasa_core.interpreter import RasaNLUInterpreter
from rasa_core.utils import EndpointConfig

# load your trained agent
interpreter = RasaNLUInterpreter("models/nlu/default/bot/")
MODEL_PATH = "models/dialogue"
action_endpoint = EndpointConfig(url="http://127.0.0.1:5500/webhook")
agent = Agent.load(MODEL_PATH, interpreter=interpreter,
                   action_endpoint=action_endpoint)

input_channel = SocketIOInput(
	# event name for messages sent from the user
	user_message_evt="user_uttered",
	# event name for messages sent from the bot
	bot_message_evt="bot_uttered",
	# socket.io namespace to use for the messages
	namespace=None
)

# set serve_forever=False if you want to keep the server running
s = agent.handle_channels([input_channel], 5500, serve_forever=True)

```

Any help appreciated and nice project by the way. Thanks in advance.

![grafik](https://user-images.githubusercontent.com/14346967/50635298-f04f3080-0f51-11e9-975b-103115b4668b.png)

**Comment by Blind0ne** [comment]
Ok I solved it :). Just add these lines of code:
```

from rasa_core.utils import EndpointConfig

action_endpoint = EndpointConfig(url="http://127.0.0.1:5055/webhook")
agent = Agent.load(MODEL_PATH, interpreter=interpreter,
                   action_endpoint=action_endpoint)
```
You can close or delete this issue :)

**Comment by Alexmhack** [comment]
Nicely done, @Blind0ne. Working with custom actions needs one more command prompt or terminal in linux which makes three in total, one for django server, second for rasa socket server and the third for custom actions.

Instead of using bot.py file you can simply run the below command also

`python -m rasa_core.run -d models/dialogue -u models/current/nlu --port 5500 --credentials credentials.yml`

And `credentials.yml` should be the same as the **rasachat/credentials.yml**

**Reopen or create another issue anytime.**

**Comment by Blind0ne** [comment]
Nice @Alexmhack even better! Thanks!

**Comment by Alexmhack** [comment]
Hey, @vkresch I needed some help with this repo. There seems to be some problem with the socket.io client-side code, each request is getting a 400 BAD REQUEST error in the browser console, can you take a look by running the code and see if it's working for you.

**Comment by ngochuyenluu** [comment]
@Alexmhack Hello, it's same situation with me. It gives always 400 when I tried to connect and chat with bot

**Comment by Alexmhack** [comment]
Have a look at this [issue](https://github.com/Alexmhack/Django-Rasa-Sockets/issues/3) and what do you think is the problem that is causing this unexpected error.

We have tried,

1. Changing code for client-side `socket.io` in **static/js/chat.js** but nothing seems to work.
2. Adding `corsheaders` to the Django backend and allowing the rasa endpoint for **CORS**.
