### ISSUE TITLE
SystemError: unknown opcode (Bot not responding..)  

### ISSUE THREAD

**Issue by BunnyStylish** [Alexmhack/Django-Rasa-Sockets#4]
Hi , when i send the message to bot, it will not respond. It will show an error like

Traceback (most recent call last):
  File "bot.py", line 17, in <module>
    s = agent.handle_channels([input_channel], 5500, serve_forever=True)
  File "C:\Users\Pulivarthi\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\agent.py", line 566, in handle_channels
    http_server.serve_forever()
  File "C:\Users\Pulivarthi\AppData\Local\Programs\Python\Python36\lib\site-packages\gevent\baseserver.py", line 369, in serve_forever
    self._stop_event.wait()
  File "src\gevent\event.py", line 127, in gevent._event.Event.wait
  File "src\gevent\_abstract_linkable.py", line 192, in gevent.__abstract_linkable.AbstractLinkable._wait
  File "src\gevent\_abstract_linkable.py", line 165, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src\gevent\_abstract_linkable.py", line 169, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src\gevent\_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\gevent\_greenlet_primitives.py", line 60, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\gevent\_greenlet_primitives.py", line 64, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\gevent\__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
SystemError: unknown opcode

How to find this please help me

**Comment by Alexmhack** [comment]
Which python version are you using to run the bot? because the bot is trained and works with python3.6 and rasa latest version

**Comment by BunnyStylish** [comment]
> Which python version are you using to run the bot? because the bot is trained and works with python3.6 and rasa latest version

I am using pyhton 3.6.4 and rasa also 1.0.0

**Comment by Alexmhack** [comment]
Try updating the rasa and gevent library to their latest version.

`pip install --upgrade rasa gevent`

**Comment by BunnyStylish** [comment]
> Try updating the rasa and gevent library to their latest version.
> 
> `pip install --upgrade rasa gevent`

Hi, After installing i got a error like 
```
Traceback (most recent call last):
  File "bot.py", line 5, in <module>
    agent = Agent.load('./models/dialogue', interpreter='./models/current/nlu')
  File "C:\Users\Pulivarthi\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa\core\agent.py", line 371, in load
    core_model, nlu_model = get_model_subdirectories(model_path)
  File "C:\Users\Pulivarthi\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa\model.py", line 152, in get_model_subdirectories
    unpacked_model_path
rasa.exceptions.ModelNotFound: No NLU or Core data for unpacked model at: './models/dialogue'.

C:\Users\Pulivarthi\RASA\Django-Rasa-Sockets-master\rasachat>

```

**Comment by BunnyStylish** [comment]
> Try updating the rasa and gevent library to their latest version.
> 
> `pip install --upgrade rasa gevent`

`rasa.nlu.model.UnsupportedModelError: The model version is to old to be loaded by this Rasa NLU instance. Either retrain the model, or run withan older version. Model version: 0.0.0 Instance version: 1.0.9`

**Comment by Alexmhack** [comment]
Yep now you need to retrain your models with the new version so run,

**Train model**
```
python -m rasa_nlu.train -c nlu_config.yml --data nlu.md -o models --fixed_model_name nlu --project current --verbose

python -m rasa_core.train -d domain.yml -s stories.md -o models/dialogue
```

Then try running the bot again.

**Comment by BunnyStylish** [comment]
> Yep now you need to retrain your models with the new version so run,
> 
> **Train model**
> 
> ```
> python -m rasa_nlu.train -c nlu_config.yml --data nlu.md -o models --fixed_model_name nlu --project current --verbose
> 
> python -m rasa_core.train -d domain.yml -s stories.md -o models/dialogue
> ```
> 
> Then try running the bot again.

Thank you for replying and supporting @Alexmhack. The above commands are not worked for me. Because of i am using updated version of rasa. I configure everything in updated rasa. Now bot is working. 
Thank you

**Comment by Alexmhack** [comment]
Alright, @BunnyStylish. Can you please write the updated commands that worked for you I will update the repo accordingly.

One more thing, can you check out this [issue](https://github.com/Alexmhack/Django-Rasa-Sockets/issues/3). Are you facing the same problem with this repo?

**Comment by BunnyStylish** [comment]
Present version of rasa: 
  Train the model:  ` rasa train`
  run the project :  ` rasa run`


I am also facing the same issue

![image](https://user-images.githubusercontent.com/53078116/64672713-d7583100-d489-11e9-9626-fc1033852189.png)

But after i change the index.html file it's worked.

**Comment by Alexmhack** [comment]
I see you are using windows, how did you manage to install the new version of rasa on windows, I am getting an error while installing `rasa-x` & `rasa` .

**Comment by BunnyStylish** [comment]
What error you are facing?
Please follow this  https://rasa.com/docs/rasa/user-guide/installation/
Everything installing in administrative mode

**Comment by Alexmhack** [comment]
```
Failed to build httptools
...

  Running setup.py install for httptools ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\pranav\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\pranav\\AppData\\Local\\Temp\\pip-install-dl7b1366\\httptools\\setup.py'"'"'; __file__='"'"'C:\\Users\\pranav\\AppData\\Local\\Temp\\pip-install-dl7b1366\\httptools\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\pranav\AppData\Local\Temp\pip-record-l6zbqj_o\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\pranav\AppData\Local\Temp\pip-install-dl7b1366\httptools\
    Complete output (21 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\httptools
    copying httptools\__init__.py -> build\lib.win-amd64-3.7\httptools
    creating build\lib.win-amd64-3.7\httptools\parser
    copying httptools\parser\errors.py -> build\lib.win-amd64-3.7\httptools\parser
    copying httptools\parser\__init__.py -> build\lib.win-amd64-3.7\httptools\parser
    running egg_info
    writing httptools.egg-info\PKG-INFO
    writing dependency_links to httptools.egg-info\dependency_links.txt
    writing top-level names to httptools.egg-info\top_level.txt
    reading manifest file 'httptools.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'httptools.egg-info\SOURCES.txt'
    copying httptools\parser\parser.c -> build\lib.win-amd64-3.7\httptools\parser
    running build_ext
    building 'httptools.parser.parser' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\pranav\appdata\local\programs\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\pranav\\AppData\\Local\\Temp\\pip-install-dl7b1366\\httptools\\setup.py'"'"'; __file__='"'"'C:\\Users\\pranav\\AppData\\Local\\Temp\\pip-install-dl7b1366\\httptools\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\pranav\AppData\Local\Temp\pip-record-l6zbqj_o\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.
```

It is asking for **Microsoft Visual C++ 14.0**, I tried this in admin command prompt.

**Comment by BunnyStylish** [comment]
Microsoft Visual C++ 14.0 it must be installed in your system 
Visual studio

**Comment by Alexmhack** [comment]
Thanks @BunnyStylish. I think this issue is solved, open anytime.

**Comment by Alexmhack** [comment]
Well, the [rasa-webchat](https://github.com/mrbot-ai/rasa-webchat) UI that you are using is itself forked from [Wolox/react-chat-widget](https://github.com/Wolox/react-chat-widget) which uses React JS as backend. Check out **rasa-webchat** source code and make changes in there to match your needs.

They detect the type of message using [this](https://github.com/mrbot-ai/rasa-webchat/blob/master/src/components/Widget/msgProcessor.js)
