### ISSUE TITLE
Getting Error: rasa.nlu.model.UnsupportedModelError

### ISSUE THREAD

**Issue by BunnyStylish** [Alexmhack/Django-Rasa-Sockets#5]
when i am run the py bot.py it showing error like this

`rasa.nlu.model.UnsupportedModelError: The model version is to old to be loaded by this Rasa NLU instance. Either retrain the model, or run withan older version. Model version: 0.0.0 Instance version: 1.0.9
`

**Comment by Alexmhack** [comment]
Have you tried updating the rasa to the latest version, check out [here](https://rasa.com/docs/getting-started/#try-rasa)
